services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=shopapi;Username=shopapi;Password=shopapi123
      Redis__Enabled: "true"
      Redis__ConnectionString: redis:6379
      Jwt__Key: shopapi-docker-secret-key-min-32-chars-long-2026
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: shopapi
      POSTGRES_USER: shopapi
      POSTGRES_PASSWORD: shopapi123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
